# Generated by Django 4.1.3 on 2022-11-09 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0004_services_remove_whychooseusmessage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='image',
            field=models.ImageField(default=1, upload_to='services/'),
            preserve_default=False,
        ),
    ]
