# Generated by Django 4.1.3 on 2022-11-09 08:44

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0005_alter_services_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='image',
        ),
        migrations.AddField(
            model_name='services',
            name='image1',
            field=django_resized.forms.ResizedImageField(crop=None, default=1, force_format=None, keep_meta=True, quality=-1, scale=None, size=[29, 27], upload_to='services/'),
            preserve_default=False,
        ),
    ]
