# Generated by Django 4.1.3 on 2022-11-09 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0006_remove_services_image_services_image1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='image1',
            new_name='image',
        ),
    ]
