# Generated by Django 4.1.3 on 2022-11-09 10:37

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0008_rename_title1_p_cupponcardprices_price_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='PNG', keep_meta=True, quality=-1, scale=None, size=[29, 27], upload_to='services/'),
        ),
    ]
