# Generated by Django 4.1.3 on 2022-11-09 10:57

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0009_alter_services_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAndOffers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='PNG', keep_meta=True, quality=-1, scale=None, size=[29, 27], upload_to='services_and_offers/')),
            ],
        ),
    ]
