# Generated by Django 4.1.3 on 2022-11-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0014_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='skype',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='telegram',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='contact',
            name='whatsapp_number',
            field=models.CharField(max_length=25),
        ),
    ]
