# Generated by Django 4.1.3 on 2022-11-11 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0015_contact_skype_contact_telegram_alter_contact_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='whatsapp_number',
            new_name='whatsapp',
        ),
    ]
