# Generated by Django 4.1.3 on 2022-11-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0016_rename_whatsapp_number_contact_whatsapp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='open_time',
        ),
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='skype',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='telegram',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
